Selenium Approach to Accessors
saucelabs/simple_sauce pull request #105
Opened 2019-12-28 04:38 UTC by titusfortner

Regardless of the With Statements, we need a baseline approach to setting values.
We should either follow the NetBeans Approach or the Selenium Approach. This is the Selenium Approach.

(This is getting compared to a branch with no accessors just to see an apples-to-apples comparison)

Pro: 
* Enums protect users from incorrect values
* List of allowed capabilities allows us to throw an exception if something is not recognized
* Easy to toggle fluent support
* More Straightforward implementation 

Con:
* No checks on valid types of capabilities
* No easy to see list of what capabilities are allowed

This is what it looks like. Note that we can have these be fluent or not. You know my preference, but it's not the hill I want to die on. :)

```java
        FirefoxOptions firefoxOptions = new FirefoxOptions();
        firefoxOptions.addArguments("--foo");
        firefoxOptions.addPreference("foo", "bar");
        sauceOptions = new SauceOptions(firefoxOptions);

        sauceOptions.setCapability("pageLoadStrategy", Options.PageLoadStrategy.EAGER);
                                .setCapability("acceptInsecureCerts", true);
                                .setCapability("unhandledPromptBehavior", Options.UnhandledPromptBehavior.IGNORE);

        Map<Options.Timeouts, Integer> timeouts = new HashMap<>();
        timeouts.put(Options.Timeouts.IMPLICIT, 1);
        timeouts.put(Options.Timeouts.PAGE_LOAD, 100);
        timeouts.put(Options.Timeouts.SCRIPT, 10);
        sauceOptions.setCapability("timeouts", timeouts);
        sauceOptions.setCapability("extendedDebugging", true);
        sauceOptions.setCapability("name", "Test name");
        sauceOptions.setCapability("parentTunnel", "Mommy");
```

I'm not sure it is the best way to do it, but I namespaced all of the enums under `Options` which I think should make it easier to see what is available? Let me know if that's dumb, I can change it.

* An exception is thrown if the capability is not recognized
* This converts String values to Enum values where possible, though that might be confusing since we aren't type checking anything, and users may want to get/set compare and this will prevent that
* Overall this implementation is more straightforward, but much less helpful to the end user.

2019-12-30 16:26 UTC, nadvolod commented
```
FirefoxOptions firefoxOptions = new FirefoxOptions();
firefoxOptions.addArguments("--foo");
firefoxOptions.addPreference("foo", "bar");
sauceOptions = new SauceOptions(firefoxOptions);
```
^^^ This part makes sense. Clean and simple, just reusing what Selenium gives us.

```
// setCapability() takes String / Object / Enum values as necessary
sauceOptions.setCapability("pageLoadStrategy", Options.PageLoadStrategy.EAGER)
            .setCapability("acceptInsecureCerts", true)
            .setCapability("unhandledPromptBehavior", "ignore);
```
^^^ No matter how hard I try, I see little value in having the ability to pass in strings into `setCapability()`. Extremely error prone and zero guidance form the IDE regarding what's possible. I prefer our users don't rely on our documentation which has never been really good and I have lots of doubts if it ever will be. Rather, I want them to rely on us to provide a clean API that they can navigate in their IDE.

2019-12-30 16:40 UTC, nadvolod reviewed
```
FirefoxOptions firefoxOptions = new FirefoxOptions();
firefoxOptions.addArguments("--foo");
firefoxOptions.addPreference("foo", "bar");
sauceOptions = new SauceOptions(firefoxOptions);
```
^^^ This part makes sense. Clean and simple, just reusing what Selenium gives us.
```
// setCapability() takes String / Object / Enum values as necessary
sauceOptions.setCapability("pageLoadStrategy", Options.PageLoadStrategy.EAGER)
            .setCapability("acceptInsecureCerts", true)
            .setCapability("unhandledPromptBehavior", "ignore);
```
^^^ No matter how hard I try, I see little value in having the ability to pass in strings into `setCapability()`. Extremely error prone and zero guidance form the IDE regarding what's possible. I prefer our users don't rely on our documentation which has never been really good and I have lots of doubts if it ever will be. Rather, I want them to rely on us to provide a clean API that they can navigate in their IDE.

2019-12-30 19:37 UTC, titusfortner commented
Yeah, compared to the Java Beans approach there is a lot less protection for users. If we go this route, we can't enforce Type and if we can't enforce Type, we'd have to support string values like this.

The more generic use case for when we need to be able to accept String values is for this situation: #109

2019-12-31 02:51 UTC, joshmgrant requested changes
Declining this in favour of #106

2020-01-02 18:30 UTC, titusfortner commented
We've agreed to do #106 instead of this.

2020-01-02 18:30 UTC, closed without merging