updated defaults for safari
saucelabs/simple_sauce pull request #139
Opened 2020-03-09 19:57 UTC by joshmgrant

In response to issue #28, the changes here are to default nicely to Safari 12 on Mojave.

2020-03-09 19:59 UTC, nadvolod commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- python/saucebindings/options.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/SauceLabs/simple_sauce/pullRequest?prid=5148112&bid=16909292)

2020-03-09 19:59 UTC, nadvolod commented on python/saucebindings/options.py
> +
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Trailing whitespace](https://app.codacy.com/manual/SauceLabs/simple_sauce/pullRequest?prid=5148112)

2020-03-09 20:13 UTC, nadvolod commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/saucebindings/options.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/SauceLabs/simple_sauce/pullRequest?prid=5148112&bid=16909292)

2020-03-09 20:25 UTC, nadvolod commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/saucebindings/options.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/SauceLabs/simple_sauce/pullRequest?prid=5148112&bid=16909292)

2020-03-09 20:48 UTC, nadvolod commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/saucebindings/options.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/SauceLabs/simple_sauce/pullRequest?prid=5148112&bid=16909292)

2020-03-10 13:17 UTC, titusfortner requested changes
@joshmgrant thanks for doing this, but the more I think about it, the more I don't think we should do this right now.
This implementation won't work for:
```
SauceOptions(browserName='safari', browserVersion='8.0')
```
We can have code to auto-select based on browser type being empty, or create default browser type based on Platform specified, but I don't think this is beta implementation.

2020-03-10 13:20 UTC, titusfortner commented
We should re-visit this post-beta with #141 
For now I think we want to expect users to be explicit.

2020-03-10 13:20 UTC, closed without merging