Website update w/ Docusaurus 3
saucelabs/simple_sauce pull request #313
Opened 2024-07-31 20:53 UTC by nadvolod

# One-line summary

Updating Sauce Bindings website to match the latest content

## Description
Updating Sauce Bindings docs to show the latest API changes for Junit5
Updating Docusaurus to 3.x

## Types of Changes
_What types of changes does your code introduce? Keep the ones that apply:_

- Configuration change
- Refactor/improvements
- Documentation / non-code

## Tasks
_List of tasks you will do to complete the PR_
  - [ ] Update all the docs
  - [ ] Test website for navigation
  - [ ] Test website for instructions

## Review
_List of tasks the reviewer must do to review the PR_
- [ ] Tests
- [ ] Documentation
- [ ] CHANGELOG

## Deployment Notes

2024-08-01 08:43 UTC, diemol requested changes

2024-08-01 08:43 UTC, diemol commented on website/blog/2019-05-28-first-blog-post.md
> +Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque elementum dignissim ultricies. Fusce rhoncus ipsum tempor eros aliquam consequat. Lorem ipsum dolor sit amet
I believe this is not needed.

2024-08-01 08:43 UTC, diemol commented on website/blog/2019-05-29-long-blog-post.md
> +
I believe this file is not needed.

2024-08-01 08:43 UTC, diemol commented on website/blog/2021-08-01-mdx-blog-post.mdx
> +Blog posts support [Docusaurus Markdown features](https://docusaurus.io/docs/markdown-features), such as [MDX](https://mdxjs.com/).
I believe this file is not needed.

2024-08-01 08:43 UTC, diemol commented on website/blog/2021-08-26-welcome/docusaurus-plushie-banner.jpeg
I believe this file is not needed.

2024-08-01 08:43 UTC, diemol commented on website/blog/2021-08-26-welcome/index.md
> +- `2019-05-30-welcome/index.md`
I believe this file is not needed.

2024-08-01 08:43 UTC, diemol commented on website/blog/authors.yml
> +  title: Docusaurus maintainer
I believe this file is not needed.

2024-08-01 08:43 UTC, diemol commented on website/blog/tags.yml
> +  label: Docusaurus
I believe this file is not needed.

2024-08-01 08:43 UTC, diemol commented on website/docs/core-concepts/Roadmap.md
> +* UPDATE ME
Maybe we can remove this page because committing to a public roadmap is hard.

2024-08-01 08:43 UTC, diemol commented on website/docs/core-concepts/configuration.md
> -id: configurations
Isn't the `id` needed?

2024-08-01 08:43 UTC, diemol commented on website/docs/core-concepts/test-runners.md
> -id: test-runners
Don't you need the `id`?

2024-08-01 08:43 UTC, diemol commented on website/docs/getting-started/first-test.md
> +<TabItem value="junit5">
What if we load the examples from the actual code?
https://docusaurus.io/docs/markdown-features/code-blocks#usage-in-jsx

Not a must for this initial revamp, but it will make the docs more maintainable.

2024-08-01 08:43 UTC, diemol commented on website/src/components/HomepageFeatures/index.js
> +  },
I believe this file is not needed.

2024-08-01 08:43 UTC, diemol commented on website/src/components/HomepageFeatures/styles.module.css
> +.featureSvg {
I believe this file is not needed.

2024-08-01 08:43 UTC, diemol commented on website/src/pages/markdown-page.md
> +You don't need React to write simple standalone pages.
I believe this file is not needed.

2024-08-01 08:43 UTC, diemol commented on website/static/img/docusaurus-social-card.jpg
I believe this file is not needed.

2024-08-01 08:43 UTC, diemol commented on website/static/img/docusaurus.png
I believe this file is not needed.

2024-08-01 08:43 UTC, diemol commented on website/static/img/logo.svg
I believe this file is not needed.

2024-08-01 08:43 UTC, diemol commented on website/static/img/sauce-bindings.png
The file is quite heavy. Can you use a compressing tool? Like https://tinypng.com/

2024-08-01 08:43 UTC, diemol commented on website/static/img/undraw_docusaurus_mountain.svg
This file is not needed.

2024-08-01 08:43 UTC, diemol commented on website/static/img/undraw_docusaurus_react.svg
This file is not needed.

2024-08-01 08:43 UTC, diemol commented on website/static/img/undraw_docusaurus_tree.svg
This file is not needed.

2024-08-14 18:41 UTC, waggledans commented
this PR is merged in https://github.com/saucelabs/sauce_bindings/pull/315

2024-08-14 18:41 UTC, closed without merging